title: Pressto Docs
description: Documentation for Pressto
theme: just-the-docs
logo: /assets/images/logo.svg
favicon_ico: /assets/images/favicon.ico

url: https://docs.heypressto.ai
color_scheme: pressto

aux_links:
  Pressto Homepage: https://heypressto.ai
